apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - rbac.yaml
  - device-plugin.yaml
  - display.yaml
images:
  - name: ghcr.io/ukd1/pi-rack-display
    digest: sha256:d0584cdaffb54ab40afd707d6a28f8ec75feea66317fbc3d8256990e71607f2f
