apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - rbac.yaml
  - device-plugin.yaml
  - display.yaml
images:
  - name: ghcr.io/ukd1/pi-rack-display
    digest: sha256:adda0b816a74606a1161600fb08de2ddb04ebd440b91374ba1a45d5be7389162
