apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - rbac.yaml
  - device-plugin.yaml
  - display.yaml
images:
  - name: ghcr.io/ukd1/pi-rack-display
    digest: sha256:af290fe51596b097d65c58b26bd4079f255740e0b37271b4fa0891ee0c1bd330
