apiVersion: v1
kind: ServiceAccount
metadata:
  name: pi-rack-display
  namespace: pi-rack-display
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pi-rack-display
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["nodes"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pi-rack-display
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pi-rack-display
subjects:
  - kind: ServiceAccount
    name: pi-rack-display
    namespace: pi-rack-display
